apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: nodeperfmon
  name: nodeperfmon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: nodeperfmon
      tier: node
  template:
    metadata:
      labels:
        component: nodeperfmon
        tier: node
    spec:
      #nodeName: $nodeName
      containers:
        - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - sh
            - -c
            - |
              cd /tmp
              git clone https://github.com/OvidiuBorlean/nodeperfmon
              cd nodeperfmon
              chmod +x ./cpucheck.sh
              chmod +x ./memcheck.sh
              echo "Installing Python Libraries"
              apt install python3-pip -y
              pip3 install azure.storage.blob
              python3 nodeperfmon.py
              sleep 600
          image: alpine
          imagePullPolicy: IfNotPresent
          name: disable-node-exporter-service
          resources:
            requests:
              cpu: 10m
          securityContext:
            privileged: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: OnDelete
EOF

sleep 5
kubectl create -f ./ds.yaml
echo "Done Creating DaemonSet"
podName=$(kubectl get pod -n kube-system | grep node-logs-exporter | cut -d ' ' -f1|tr '\n' ' ' |  rev | cut -c 2- | rev)
echo  "kubectl cp kube-system/$podName:/tmp/akslogs.tgz ./akslogs.tgz" > ./copy
chmod +x ./copy
echo "Getting Archive"
./copy
rm ./ds.yaml
rm ./copy
echo Done
