apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: nodeperfmon
  name: nodeperfmon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: nodeperfmon
      tier: node
  template:
    metadata:
      labels:
        component: nodeperfmon
        tier: node
    spec:
      #nodeName: $nodeName
      containers:
        - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - sh
            - -c
            - |
              cd /tmp
              git clone https://github.com/OvidiuBorlean/nodeperfmon
              cd nodeperfmon
              cat << EOF > ./backup.sh
              #!/bin/bash
              tar -cvzf /tmp/AKS_backup.tgz /var/log/journal /var/log/azure-vnet* 
              EOF
              chmod +x ./backup.sh
              echo "Installing Python Libraries"
              apt install python3-pip -y
              pip3 install azure-storage-file-share
              pip3 install psutil
              echo "Starting Monitoring"
              python3 /tmp/nodeperfmon/fsnodeperfmon.py
              sleep 600
          image: alpine
          env:
          - name: CONN_STR
            value: "DefaultEndpointsProtocol=https;AccountName=akwwinlogs;AccountKey=A3F4dcB+8wPjFlfvI8fF29ku+5BsMYDfTE7zfi2Ryv2JTxTxCDlRSk0n5IVRuiDKS6rNh3PBgbSO+ASt4ePRRw==;EndpointSuffix=core.windows.net"
          - name: CPU_MAX
            value: "85"
          - name: MEM_MAX
            value: "5"
          
          imagePullPolicy: IfNotPresent
          name: disable-node-exporter-service
          resources:
            requests:
              cpu: 10m
          securityContext:
            privileged: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: OnDelete