apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: nodeperfmon
  name: nodeperfmon
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: nodeperfmon
      tier: node
  template:
    metadata:
      labels:
        component: nodeperfmon
        tier: node
    spec:
      #nodeName: $nodeName
      containers:
        - command:
            - nsenter
            - --target
            - "1"
            - --mount
            - --uts
            - --ipc
            - --net
            - --pid
            - --
            - sh
            - -c
            - |
              cd /tmp
              git clone https://github.com/OvidiuBorlean/nodeperfmon
              cd nodeperfmon
              cat << EOF > ./backup.sh
              #!/bin/bash
              tar -cvzf /tmp/AKS_backup.tgz /var/log/journal /var/log/azure-vnet* 
              EOF
              cat << EOF > ./memcheck.sh
              #!/bin/bash
              MEMORY=$(free -m | awk 'NR==2{printf "%.2f", $3*100/$2 }')
              echo $MEMORY
              EOF
              cat << EOF > ./cpucheck.sh
              #!/bin/bash
              CPU=$(top -bn1 | grep load | awk '{printf "%.2f%%\n", $(NF-2)}' | sed 's/.$//')
              echo $CPU
              EOF
              chmod +x ./cpucheck.sh
              chmod +x ./memcheck.sh
              chmod +x ./backup.sh
              echo "Installing Python Libraries"
              apt install python3-pip -y
              pip3 install azure.storage.fileshare
              echo "Starting Monitoring"
              python3 /tmp/nodeperfmon/fsnodeperfmon.py
              sleep 600
          image: alpine
          env:
          - name: CONN_STR
            value: "DefaultEndpointsProtocol=https;AccountName=ovidiuborlean;AccountKey=eD2H0KoImC1ZumdQu8bp+PP19cVKq11TLzGUhfbcDOjvCO2Mm8Zf69rmr7I1uDy9KRN2XiPTKkFA+AStiJ0tdQ==;EndpointSuffix=core.windows.net"
          - name: CPU_MAX
            value: "85"
          - name: MEM_MAX
            value: "5"
          
          imagePullPolicy: IfNotPresent
          name: disable-node-exporter-service
          resources:
            requests:
              cpu: 10m
          securityContext:
            privileged: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
      restartPolicy: Always
  updateStrategy:
    type: OnDelete